/*
 * This source file was generated by the Gradle 'init' task
 */
package taller5;
import java.text.DecimalFormat;
import java.util.Scanner;
public class App {
    
    public static void main(String[] args) {
        
        try {
            System.out.println("Punto 1");
            System.out.println(Encontrar_Numero());
            System.out.println("Punto 2");
            System.out.println(Simular_Ventas());
            System.out.println("Punto 3");
            System.out.println(Calcular_empaque(530));
            System.out.println("Punto 4");
            System.out.println(Jugar_21(24));
        } 
        
        catch (Exception e) {
            // TODO: handle exception
        }
    }


    /*
    
        1.	Desarrolle un algoritmo e impleméntelo en Java que: le pida al usuario un número entero positivo 
        entre 1000 y 9999. En un ciclo genere números de manera aleatoria y cuente los intentos que hizo antes 
        de hallar el número exactamente.
    
     */
    public static int Encontrar_Numero() {
        try {

            Scanner scanner = new Scanner(System.in);
            int Numero = 0;
            int Desde = 1000;
            int Hasta = 9999;
            int Rango = Hasta - Desde + 1;
            int Aleatorios = (int) (Math.random() * Rango) + Hasta;

            int Intentos = 0;

            System.out.println("Introduzca un numero entre el 1000 y 9999");
            Numero = scanner.nextInt();

            if (Numero >= Desde && Numero <= Hasta) {
                while (Aleatorios != Numero) {
                    System.out.println("Los numeros generados son: " + Aleatorios);
                    Intentos++;
                    Aleatorios = (int) (Math.random() * Rango) + Desde;
                }
                System.out.println("El numero encontardo fue:" + Numero + "\nLos intentos generados fueron: ");

            } else {
                System.out.println("El numero ingresado no es valido");
            }

            return Intentos;

        } catch (Exception e) {
            return 0;
        }

    }


    /* 
     
        2.	Se requiere una función en java que simule las Ventas de tres Años para un almacén. Para cada Año, deberá generar 
        un aleatorio para cada Mes hasta completar los 12 Meses. La función se llamará Simular_Ventas, y debe retornar un String 
        al final que muestre las Ventas de cada Año, así:
        
            Año 1
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total Ventas Año 1:  $##.###.###
            
            Año 2
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total Ventas Año 2: $##.###.###
            
            Año 3
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###

            Total Ventas Año 3: $##.###.###
            
            Investigue sobre la clase DecimalFormat para mostrar bien la salida. 
            import java.text.DecimalFormat;
            DecimalFormat Formato_Pesos = new DecimalFormat("$#,###.00");

        
      
     */
    public static String Simular_Ventas() {
        DecimalFormat Formato_Pesos = new DecimalFormat("$#,###.00");
        String Ventas = "";
        int Total_Ventas_Año;
        int Ventas_Mes = 0;
        for (int Año = 1; Año <= 3; Año++) {
            Total_Ventas_Año = 0;
            Ventas += "Año " + Año + "\n";

            for (int Mes = 1; Mes <= 12; Mes++) {
                Ventas_Mes = (int) (Math.random() * 1000000 + 50000);
                Total_Ventas_Año += Ventas_Mes;
                Ventas += "Ventas Mes " + Mes + ": " + Formato_Pesos.format(Ventas_Mes) + "\n";
            }

            Ventas += "Total Ventas Año " + Año + ": " + Formato_Pesos.format(Total_Ventas_Año) + "\n\n";
        }

        return Ventas;
    }

    /*  
     
        3.	En una fábrica se tiene el siguiente patrón de empaque: En una estiba(o Pallet) caben 16  Cajas y en cada Caja, 
        caben 30Bombillas. Desarrolle una función que se llame: Calcular_empaque que: reciba como argumento la cantidad de 
       Bombillas que se deben empacar y a partir de allí: calcule cuántas Cajas necesita, cuántas estibas o Pallets necesita. 
        Luego escriba lo siguiente: 

        Para ###Bombillas, se necesitan ## Cajas y ## Pallets. Se quedan ###Bombillas sin empacar. Se empacará así:

        Pallet 1 --> Caja1, Caja2……,Caja16
        Pallet2 -->  Caja17, Caja18…..Caja 32
        .
        Pallet n -- > Caja m, Caja m+1…..
        
        La función retornará un texto, con la información anterior. Pruebe la función llamándola desde el programa principal: solicite al usuario el número deBombillas e invoque la función para imprimir en el main, los Resultados.



     */
    public static String Calcular_empaque(int Bombillas) {
        int Cajas_Pallet = 16;
        int Bombillas_Caja = 30;
        int Cajas_Necesarias = Bombillas / Bombillas_Caja;
        int T_Pallets = Cajas_Necesarias / Cajas_Pallet;
        int Cajas_Sobrantes = Cajas_Necesarias % Cajas_Pallet;
        int Bombillas_Sobrantes = Bombillas % Bombillas_Caja;

        String Resultado = "Para " + Bombillas + " Bombillas, se necesitan "
                + Cajas_Necesarias + " Cajas y " + T_Pallets + " Pallets.\n"
                + "Se quedan " + Bombillas_Sobrantes + " Bombillas sin empacar.\n"
                + "Se empacará así:\n";

        int Caja_Actual = 1;
        for (int Pallet = 1; Pallet <= T_Pallets; Pallet++) {
            Resultado += "Pallet " + Pallet + " --> ";
            for (int Caja = 1; Caja <= Cajas_Pallet; Caja++) {
                Resultado += "Caja" + Caja_Actual + ", ";
                Caja_Actual++;
            }
            Resultado += "\n";
        }

        if (Cajas_Sobrantes > 0) {
            Resultado += "Pallet " + (T_Pallets + 1) + " --> ";
            for (int Caja = 1; Caja <= Cajas_Sobrantes; Caja++) {
                Resultado += "Caja" + Caja_Actual + ", ";
                Caja_Actual++;
            }
            Resultado += "\n";
        }

        return Resultado;
    }

    /* 
    

        4.	En un juego, cada jugador tiene 3 intentos para sacar cartas de una baraja. Las cartas van numeradas entre 1 y 10. 
        Una función Jugar_21, deberá simular el juego para una cantidad de usuarios que enviará el usuario desde el main entre 1 y 6.

        Para cada uno de los jugadores, el programa le calculará 3 cartas al azar y al final imprimirá el juego para cada jugador basado en las siguientes reglas: 
        
        Si saca 21 exactos: juego perfecto
        Si saca más de 21: se pasó
        Si saca menos de 21: faltaron puntos

        La función deberá imprimir los puntos de cada jugador junto con la regla anterior, como muestra el ejemplo:

        Jugador X, puntos 21 -- > juego perfecto
        Jugador Y, puntos 26 -- > se pasó
        .
        .


     */
    public static String Jugar_21(int jugadores) {
        String resultado = "";

        for (int jugador = 1; jugador <= jugadores; jugador++) {
            int puntos = 0;

            for (int intento = 1; intento <= 3; intento++) {
                int carta = (int) (Math.random() * 10) + 1;
                puntos += carta;
            }

            resultado += "Jugador " + jugador + ", puntos " + puntos + " --> ";

            if (puntos == 21) {
                resultado += "juego perfecto\n";
            } else if (puntos > 21) {
                resultado += "se pasó\n";
            } else {
                resultado += "faltaron puntos\n";
            }
        }

        return resultado;
    }

}

